name: Hello World
on: [push]
jobs:
  RunSomething:
    name: Run MATLAB Script
    strategy:
      matrix:
        release: [R2020b, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with: ${{ matrix.release }}
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: HelloWorld
